### PR TITLE
resizes SVG to 24x24

### LINKED ISSUE #60: Zoom Icon needs to be scaled down
In the "Recently Accessed Items" block, the icon breaks layout.

zoom svg recently accessed items

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #60

### CODE REVIEW

**Comment by jrchamp** [comment]
Thank you for your contribution. It looks like a few extra changes were made other than the resize, resulting in a 42% larger file.

On a sidenote, I've used this useful tool in the past: https://jakearchibald.github.io/svgomg/

**Comment by jrchamp** [comment]
Please try this version and let me know if it works just as well:
`<svg width="100%" height="100%" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><g transform="scale(.04688)"><circle cx="256" cy="256" r="256" fill="#3f88ff"/><path d="M346 293.737v-75.474l69.075-50.635v176.744L346 293.737z" fill="#fff"/><path d="M329 230.688c0-37.101-20.612-63.06-60.893-63.06H96.925v112.774c0 39.919 24.526 63.97 61.254 63.97H329V230.688z" fill="#fff"/></g></svg>`

**Comment by stopfstedt** [comment]
> <svg width="100%" height="100%" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><g transform="scale(.04688)"><circle cx="256" cy="256" r="256" fill="#3f88ff"/><path d="M346 293.737v-75.474l69.075-50.635v176.744L346 293.737z" fill="#fff"/><path d="M329 230.688c0-37.101-20.612-63.06-60.893-63.06H96.925v112.774c0 39.919 24.526 63.97 61.254 63.97H329V230.688z" fill="#fff"/></g></svg>

will give it a go next week and get back with you. thanks!

**Comment by rlorenzo** [comment]
@stopfstedt Let me know when you are able to reduce the size of the SVG

**Comment by rlorenzo** [comment]
@jrchamp The SVG you provided was still large in my testing, but I resized the svg and seems to work for me.

**Pull request closed without merging**
